package Vista;

import Modelo.Arbol;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author LSOPORTE10
 */
public class Principal extends javax.swing.JFrame {

    Arbol arbol = new Arbol();
    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        arbol.llenarArbol();
        this.setTitle("Cable");
        this.setSize(600, 350);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("A");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("B");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("D");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("H");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("I");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("E");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("J");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("K");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("F");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("L");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("M");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("G");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("N");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("O");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        Arbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                ArbolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(Arbol);

        texto.setText("Seleccione un Nodo para ver la incidencia.");
        jScrollPane2.setViewportView(texto);

        arbol.llenarArbol();
        jLabel1.setText(arbol.getGanancia(arbol.A));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Metodo ArbolValueChanged
     * Este metodo es el que esta a la escucha de un evento de tipo Select,
     * es activado cada vez que se selecciona un nodo del arbol.
     * @param evt 
     */
    private void ArbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_ArbolValueChanged
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) Arbol.getLastSelectedPathComponent();

        switch(nodo.toString()){
            case "A" :
                texto.setText(arbol.getPerdida(arbol.A)+arbol.getCasas(arbol.A));
            break;
            case "B" :
                texto.setText(arbol.getPerdida(arbol.B)+arbol.getCasas(arbol.B));
            break;
            case "C" :
                texto.setText(arbol.getPerdida(arbol.C)+arbol.getCasas(arbol.C));
            break;
            case "D" :
                texto.setText(arbol.getPerdida(arbol.D)+arbol.getCasas(arbol.D));
            break;
            case "E" :
                texto.setText(arbol.getPerdida(arbol.E)+arbol.getCasas(arbol.E));
            break;
            case "F" :
                texto.setText(arbol.getPerdida(arbol.F)+arbol.getCasas(arbol.F));
            break;
            case "G" :
                texto.setText(arbol.getPerdida(arbol.G)+arbol.getCasas(arbol.G));
            break;
            case "H" :
                texto.setText(arbol.getPerdida(arbol.H)+arbol.getCasas(arbol.H));
            break;
            case "I" :
                texto.setText(arbol.getPerdida(arbol.I)+arbol.getCasas(arbol.I));
            break;
            case "J" :
                texto.setText(arbol.getPerdida(arbol.J)+arbol.getCasas(arbol.J));
            break;
            case "K" :
                texto.setText(arbol.getPerdida(arbol.K)+arbol.getCasas(arbol.K));
            break;
            case "L" :
                texto.setText(arbol.getPerdida(arbol.L)+arbol.getCasas(arbol.L));
            break;
            case "M" :
                texto.setText(arbol.getPerdida(arbol.M)+arbol.getCasas(arbol.M));
            break;
            case "N" :
                texto.setText(arbol.getPerdida(arbol.N)+arbol.getCasas(arbol.N));
            break;
            case "O" :
                texto.setText(arbol.getPerdida(arbol.O)+arbol.getCasas(arbol.O));
            break;
        }
    }//GEN-LAST:event_ArbolValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
